### ISSUE TITLE
«Call to a member function getRealOrderId() on null in vendor/magento/module-sales/Block/Order/PrintShipment.php:60»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [inkifi/site#8]
Stack trace:
```
#0 vendor/magento/framework/View/Element/AbstractBlock.php(272): Magento\Sales\Block\Order\PrintShipment->_prepareLayout()
inkifi/pwinty#1 vendor/magento/framework/View/Layout/Generator/Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
inkifi/pwinty#2 vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
inkifi/pwinty#3 vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(M
File: vendor/magento/module-sales/Block/Order/PrintShipment.php
Line: 60
```

**Comment by dmitry-fedyuk** [comment]
It is occured when a customer tries to print his order, e.g.:
![01](https://user-images.githubusercontent.com/83204/75810013-ef16cf00-5db3-11ea-8002-0267823583e8.png)

**Comment by dmitry-fedyuk** [comment]
https://github.com/magento/magento2/issues/9830

**Comment by dmitry-fedyuk** [comment]
The fix: https://github.com/magento/magento2/pull/11631/files

**Comment by dmitry-fedyuk** [comment]
The solution is to add `cacheable='false' attribute to all `Magento\Sales\Block\Order\PrintShipment` blocks, e.g.: https://github.com/magento/magento2/blob/2.3.4/app/code/Magento/Sales/view/frontend/layout/sales_order_print.xml#L15-L18
